"""Mathematical models and kinetics."""

from bioprocess_twin.models.chemistry import (
    AlbaDissociationConstantsRef,
    AlbaDissociationEnthalpy,
    AqueousSpeciesMolar,
    ChargeBalanceInputs,
    PHSolveError,
    PHSolveResult,
    PHSolverOptions,
    SpeciationTotals,
    charge_residual,
    default_dissociation_constants_ref_molar,
    default_dissociation_enthalpy_j_per_mol,
    solve_pH,
    speciate_aqueous,
    speciate_from_alba_totals,
)
from bioprocess_twin.models.gas_transfer import (
    T_REF_CELSIUS_KLA,
    GasTransferConditions,
    GasTransferRates,
    HenryConstantsGas,
    calculate_gas_transfer,
    diffusivity_ratio_sqrt_co2,
    diffusivity_ratio_sqrt_nh3,
    effective_kla_o2_per_day,
    henry_o2_co2_nh3,
    kinetic_kla_factor,
    liquid_volatile_co2_gC_per_m3,
    liquid_volatile_nh3_gN_per_m3,
)
from bioprocess_twin.models.hydrochemistry_api import (
    HydrochemistryStepResult,
    hydrochemistry_step,
    solve_pH_from_state,
    speciation_totals_from_state,
)
from bioprocess_twin.models.kinetic_modifiers import (
    f_do_decay_hill,
    f_do_growth_hill,
    f_i_haldane,
    f_ph_cpm,
    f_t_decay_arrhenius,
    f_t_growth_ctmi,
)
from bioprocess_twin.models.kinetic_parameters import (
    CardinalPH,
    CardinalTemperature,
    KineticParameters,
    default_alba,
)
from bioprocess_twin.models.kinetics import EnvConditions, calculate_rates

__all__ = [
    "HydrochemistryStepResult",
    "hydrochemistry_step",
    "solve_pH_from_state",
    "speciation_totals_from_state",
    "GasTransferConditions",
    "GasTransferRates",
    "HenryConstantsGas",
    "T_REF_CELSIUS_KLA",
    "calculate_gas_transfer",
    "diffusivity_ratio_sqrt_co2",
    "diffusivity_ratio_sqrt_nh3",
    "effective_kla_o2_per_day",
    "henry_o2_co2_nh3",
    "kinetic_kla_factor",
    "liquid_volatile_co2_gC_per_m3",
    "liquid_volatile_nh3_gN_per_m3",
    "AlbaDissociationConstantsRef",
    "AlbaDissociationEnthalpy",
    "AqueousSpeciesMolar",
    "CardinalPH",
    "CardinalTemperature",
    "ChargeBalanceInputs",
    "EnvConditions",
    "KineticParameters",
    "PHSolveError",
    "PHSolveResult",
    "PHSolverOptions",
    "SpeciationTotals",
    "calculate_rates",
    "charge_residual",
    "default_alba",
    "default_dissociation_constants_ref_molar",
    "default_dissociation_enthalpy_j_per_mol",
    "solve_pH",
    "speciate_aqueous",
    "speciate_from_alba_totals",
    "f_do_decay_hill",
    "f_do_growth_hill",
    "f_i_haldane",
    "f_ph_cpm",
    "f_t_decay_arrhenius",
    "f_t_growth_ctmi",
]
